apiVersion: v1
kind: Service
metadata:
    name: toreview
    labels:
        name: comms
        app: applytics
spec:
    ports:
    - port: 3000
       targetPort: 65534
    selector:
        app: applytics